### ISSUE TITLE
Fatal error: Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by neszt** [helmo/roundcube-behat-checker#2]
Running "vendor/bin/behat" i get an error:
```
roundcube-behat-checker# vendor/bin/behat
Feature: Roundcube should work

  Background:                                                            # features/roundcube.feature:3
    Given there is an roundcube server at "https://webmail.*************.hu/" # FeatureContext::thereIsAnRoundcubeServerAt()
    And there is an account defined by the environment                   # FeatureContext::thereIsAnAccountDefinedByTheEnvironment()

  Scenario: Logging in                               # features/roundcube.feature:7
    When I log in                                    # FeatureContext::iLogIn()
    Fatal error: Class 'DOMDocument' not found (Behat\Testwork\Call\Exception\FatalThrowableError)
    Then I should get a 2xx http response            # FeatureContext::iShouldGetAHttpResponse()
    And I should have the element "#mailview-bottom" # FeatureContext::iShouldHaveTheElement()
```

**Comment by helmo** [comment]
`composer update` might help there, could be releated to you having a different php version to me when I committed this.

**Comment by neszt** [comment]
Exactly what php version is required? I tried it on Debian Buster:
```
$ docker run -it --rm debian:buster
```

**Comment by helmo** [comment]
That was running on a Debian Stretch VM with php 7.0.33

I've now done a `composer update` on a Buster VM and then it also works for me. 
I hope commit fd15c7564a67d86b541171f6f7255a2be040c622 which is now on master helps you.

However I got a different error there `Warning: count(): Parameter must be an array or an object that implements Countable in vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 67`

**Comment by neszt** [comment]
Thanks for the help! However, it's still not working. I made a pull request, you can see how i try.

**Comment by helmo** [comment]
Good idea to create a docker setup in #3 

Adding the Debian package `php-fdomdocument` seems to help. Atleast then I move on to a `Invalid status code 401 (Exception)`

Not sure why that is though, it's picking the right server and copy/pasting the credentials from `.env` works.

**Comment by neszt** [comment]
New package php-fdomdocument solved the DOMDocument error. Other, "Element not found exeption" errors appeared. Is it possible that these are due to the version of roundcube? My tests run on Roundcube Webmail 1.3.7.

```
Feature: Roundcube should work

  Background:                                                           # features/roundcube.feature:3
    Given there is an roundcube server at "https://webmail.************.hu" # FeatureContext::thereIsAnRoundcubeServerAt()
    And there is an account defined by the environment                  # FeatureContext::thereIsAnAccountDefinedByTheEnvironment()

  Scenario: Logging in                               # features/roundcube.feature:7
    When I log in                                    # FeatureContext::iLogIn()
    Then I should get a 2xx http response            # FeatureContext::iShouldGetAHttpResponse()
    And I should have the element "#mailview-bottom" # FeatureContext::iShouldHaveTheElement()
      Element not found (Exception)

  Scenario: Sending an email                           # features/roundcube.feature:12
    When I log in                                      # FeatureContext::iLogIn()
    And I go to task "mail" action "compose"           # FeatureContext::iGoToTaskAction()
    Then I should have the element "#composeoptions"   # FeatureContext::iShouldHaveTheElement()
      Element not found (Exception)
    When I submit the email page with the information: # FeatureContext::iSubmitTheEmailPageWithTheInformation()
      | field     | value                 |
      | recipient | nagios@example.com    |
      | subject   | Test email from behat |
      | body      | Hello world           |

  Scenario: Check if the password change plugin exists   # features/roundcube.feature:22
    When I log in                                        # FeatureContext::iLogIn()
    And I go to task "settings" action "plugin.password" # FeatureContext::iGoToTaskAction()
    Then I should have the element "#newpasswd"          # FeatureContext::iShouldHaveTheElement()
      Element not found (Exception)

  Scenario: Check if spamassassin plugin exists             # features/roundcube.feature:27
    When I log in                                           # FeatureContext::iLogIn()
    And I go to task "settings" action "plugin.sauserprefs" # FeatureContext::iGoToTaskAction()
    Then I should have the element "#rcmrowbayes"           # FeatureContext::iShouldHaveTheElement()
      Element not found (Exception)

--- Failed scenarios:

    features/roundcube.feature:7
    features/roundcube.feature:12
    features/roundcube.feature:22
    features/roundcube.feature:27

4 scenarios (4 failed)
21 steps (16 passed, 4 failed, 1 skipped)
0m0.72s (10.56Mb)
```

**Comment by helmo** [comment]
I suspect the theme. This was created on the Larry theme.

I've upgraded since to roundcube 1.4.9+dfsg.1-1~bpo10+1 and not seen such errors, but the test account has Larry in the settings.

**Comment by helmo** [comment]
I found that the variables were not being used in docker which was why it failed in my earlier tests.

I've now re-arraged the docker files a bit
- run as a regular user not root
- do not clone from github, but use the local dir ... thus being able to use edited feature files.
- Add more variables to variables.sh
 
Hope this works for you.
